# Generated by Django 4.2.4 on 2023-08-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_collection_featured_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='featured_product_id',
            new_name='featured_product',
        ),
    ]
