# Generated by Django 4.2.4 on 2023-08-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_featured_product_id_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_updated',
            new_name='last_update',
        ),
    ]
